name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm ci
        npm run build --if-present
    - name: Upload build directory
      uses: actions/upload-artifact@v3
      with:
        name: build-directory
        path: build  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build directory
      uses: actions/download-artifact@v3
      with:
        name: build-directory
        path: build
    - name: Upload
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build # The folder the action should deploy.